name: sync-clustersetimage-cron

on:
  schedule:
    - cron:  '0 3 * * *'
  workflow_dispatch: {}  
jobs:
  sync-clusterimageset-release-2_3:
    name: sync-clusterimageset-release-2.3
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: sync-clusterimageset
        run: make sync-images-job
        env:
          TARGET_BRANCH: release-2.3
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./clusterImageSets
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: release-2.3
          keep_files: true
          destination_dir: clusterImageSets

  sync-clusterimageset-release-2_4:
    name: sync-clusterimageset-release-2.4
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: sync-clusterimageset
        run: make sync-images-job
        env:
          TARGET_BRANCH: release-2.4
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./clusterImageSets
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: release-2.4
          keep_files: true
          destination_dir: clusterImageSets

  sync-clusterimageset-release-2_5:
    name: sync-clusterimageset-release-2.5
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: sync-clusterimageset
        run: make sync-images-job
        env:
          TARGET_BRANCH: release-2.5
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./clusterImageSets
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: release-2.5
          keep_files: true
          destination_dir: clusterImageSets

  sync-clusterimageset-release-2_6:
    name: sync-clusterimageset-release-2.6
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: sync-clusterimageset
        run: make sync-images-job
        env:
          TARGET_BRANCH: release-2.6
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./clusterImageSets
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: release-2.6
          keep_files: true
          destination_dir: clusterImageSets

  sync-clusterimageset-backplane-2_2:
    name: sync-clusterimageset-backplane-2.2
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: sync-clusterimageset
        run: make sync-images-job
        env:
          TARGET_BRANCH: backplane-2.2
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./clusterImageSets
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: backplane-2.2
          keep_files: true
          destination_dir: clusterImageSets
      
  sync-clusterimageset-backplane-2_3:
    name: sync-clusterimageset-backplane-2.3
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: sync-clusterimageset
        run: make sync-images-job
        env:
          TARGET_BRANCH: backplane-2.3
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./clusterImageSets
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: backplane-2.3
          keep_files: true
          destination_dir: clusterImageSets

  sync-clusterimageset-backplane-2_4:
    name: sync-clusterimageset-backplane-2.4
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: sync-clusterimageset
        run: make sync-images-job
        env:
          TARGET_BRANCH: backplane-2.4
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./clusterImageSets
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: backplane-2.4
          keep_files: true
          destination_dir: clusterImageSets

  sync-clusterimageset-backplane-2_5:
    name: sync-clusterimageset-backplane-2.5
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: sync-clusterimageset
        run: make sync-images-job
        env:
          TARGET_BRANCH: backplane-2.5
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./clusterImageSets
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: backplane-2.5
          keep_files: true
          destination_dir: clusterImageSets

  sync-clusterimageset-backplane-2_6:
    name: sync-clusterimageset-backplane-2.6
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: sync-clusterimageset
        run: make sync-images-job
        env:
          TARGET_BRANCH: backplane-2.6
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./clusterImageSets
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: backplane-2.6
          keep_files: true
          destination_dir: clusterImageSets

  sync-clusterimageset-backplane-2_7:
    name: sync-clusterimageset-backplane-2.7
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: sync-clusterimageset
        run: make sync-images-job
        env:
          TARGET_BRANCH: backplane-2.7
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./clusterImageSets
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: backplane-2.7
          keep_files: true
          destination_dir: clusterImageSets

  sync-clusterimageset-backplane-2_8:
    name: sync-clusterimageset-backplane-2.8
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: sync-clusterimageset
        run: make sync-images-job
        env:
          TARGET_BRANCH: backplane-2.8
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./clusterImageSets
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: backplane-2.8
          keep_files: true
          destination_dir: clusterImageSets

  sync-clusterimageset-backplane-2_9:
    name: sync-clusterimageset-backplane-2.9
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: sync-clusterimageset
        run: make sync-images-job
        env:
          TARGET_BRANCH: backplane-2.9
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./clusterImageSets
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: backplane-2.9
          keep_files: true
          destination_dir: clusterImageSets

  sync-clusterimageset-backplane-2_10:
    name: sync-clusterimageset-backplane-2.10
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: sync-clusterimageset
        run: make sync-images-job
        env:
          TARGET_BRANCH: backplane-2.10
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./clusterImageSets
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: backplane-2.10
          keep_files: true
          destination_dir: clusterImageSets

  sync-clusterimageset-backplane-2_11:
    name: sync-clusterimageset-backplane-2.11
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: sync-clusterimageset
        run: make sync-images-job
        env:
          TARGET_BRANCH: backplane-2.11
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./clusterImageSets
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: backplane-2.11
          keep_files: true
          destination_dir: clusterImageSets
